---
title: "kaggle_credit_model"
author: "Andrew Moore"
date: "`r Sys.Date()`"
output: html_document
---

```{r, results = 'hide'}
library(knitr)
library(rmarkdown)
library(C50)
library(ggplot2)
library(kernlab)
library(lubridate)
library(matrixStats)
library(psych)
library(rminer)
library(rpart.plot)
library(rpart)
library(arules)
library(rJava)
library(RWeka)
library(dplyr)
library(tidyverse)
library(e1071)
library(caret)
library(quanteda)
library(irlba)
library(randomForest)
library(readxl)
library(quanteda.textmodels)
library(skimr)
library(recipes)
library(h2o)
library(zoo)
library(knitr)
library(gbm)
library(class)
library(vtable)
library(kableExtra)
library(gbm)
```

```{r}
## setwd("~/kaggle_credit/kaggle_credit")
test <- read.csv("application_test.csv", stringsAsFactors = TRUE)
train <- read.csv("application_train.csv", stringsAsFactors = TRUE)
bb <- read.csv("bureau_balance.csv", stringsAsFactors = TRUE) ##Monthly balances of previous credits
b <- read.csv("bureau.csv", stringsAsFactors = TRUE) ##All client's previous credits provided by other ifnancial institutions
ccb <- read.csv("credit_card_balance.csv", stringsAsFactors = TRUE) ##Monthly balance snapshots of previous credit cards that the applicant has with Home Credit
ip <- read.csv("installments_payments.csv", stringsAsFactors = TRUE) ##Repayment history for the previously disbursed credits in Home Credit related to the loans in our sample
pcb <- read.csv("POS_CASH_balance.csv", stringsAsFactors = TRUE) ##Monthly balance snapshots of previous POS and cash loans
pa <- read.csv("previous_application.csv", stringsAsFactors = TRUE) ##Monthly balance snapshots of previous credit cards that the applicant has with Home Credit
ss <- read.csv("sample_submission.csv", stringsAsFactors = TRUE)
```



```{r}
ggplot(data = train, aes(x = TARGET)) +
    geom_bar()
```

```{r}
ggplot(data = train, aes(x = TARGET, fill = NAME_EDUCATION_TYPE)) +
    geom_bar()

```

```{r}
ggplot(data = train, aes(x = TARGET, fill = NAME_EDUCATION_TYPE)) +
    geom_bar(position = "dodge")
```

```{r}
ggplot(data = train, aes(x = TARGET , y = EXT_SOURCE_1 )) +
    geom_boxplot()
```
```{r}
ggplot(data = train, aes(x = TARGET , y = EXT_SOURCE_2 )) +
    geom_boxplot()
```
```{r}
ggplot(data = train, aes(x = TARGET , y = EXT_SOURCE_3 )) +
    geom_boxplot()
```

```{r}
ggplot(data = train, aes(x = TARGET, fill = NAME_INCOME_TYPE)) +
    geom_bar(position = "dodge")
```

```{r}
knownTarget <- train[1:2]
train <- select(train, -TARGET)
joint <- rbind(train,test)
```


```{r}
colSums(is.na(joint))
joint <- joint[,-c(11,12,13,14,15,19,21,22,23,24,25,26,27,28,33,34,35,36,37,38,39,40,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121)]
colSums(is.na(joint))
```

```{r}
summary(joint)
st(joint)
```

```{r}
joint$AMT_ANNUITY <- na.aggregate(joint$AMT_ANNUITY, FUN = median)
joint$AMT_GOODS_PRICE <- na.aggregate(joint$AMT_GOODS_PRICE, FUN = mean)
joint$DAYS_EMPLOYED <- replace(joint$DAYS_EMPLOYED, is.na(joint$DAYS_EMPLOYED), 0)
joint$DAYS_EMPLOYED[sapply(joint$DAYS_EMPLOYED, is.numeric)] <- joint$DAYS_EMPLOYED[sapply(joint$DAYS_EMPLOYED, is.numeric)] * -1
joint$DAYS_EMPLOYED[joint$DAYS_EMPLOYED < 0] <- 0
joint$DAYS_REGISTRATION[sapply(joint$DAYS_REGISTRATION, is.numeric)] <- joint$DAYS_REGISTRATION[sapply(joint$DAYS_REGISTRATION, is.numeric)] * -1
joint$DAYS_ID_PUBLISH[sapply(joint$DAYS_ID_PUBLISH, is.numeric)] <- joint$DAYS_ID_PUBLISH[sapply(joint$DAYS_ID_PUBLISH, is.numeric)] * -1
joint$DAYS_BIRTH[sapply(joint$DAYS_BIRTH, is.numeric)] <- joint$DAYS_BIRTH[sapply(joint$DAYS_BIRTH, is.numeric)] * -1
joint$REGION_RATING_CLIENT <- as.factor(joint$REGION_RATING_CLIENT)
joint$REGION_RATING_CLIENT_W_CITY <- as.factor(joint$REGION_RATING_CLIENT_W_CITY)
joint$CNT_CHILDREN <- replace(joint$CNT_CHILDREN, is.na(joint$CNT_CHILDREN), 0)
joint$EXT_SOURCE_1 <- na.fill(joint$EXT_SOURCE_1, fill = ((joint$EXT_SOURCE_2 * joint$EXT_SOURCE_3)/2))
joint$EXT_SOURCE_2 <- na.fill(joint$EXT_SOURCE_2, fill = ((joint$EXT_SOURCE_1 * joint$EXT_SOURCE_3)/2))
joint$EXT_SOURCE_3 <- na.fill(joint$EXT_SOURCE_3, fill = ((joint$EXT_SOURCE_1 * joint$EXT_SOURCE_2)/2))
joint$CNT_FAM_MEMBERS <- na.fill(joint$CNT_FAM_MEMBERS, fill = 1)
```

```{r}
summary(joint)
```
```{r}
joint <- joint %>%
  mutate(ADULTS = CNT_FAM_MEMBERS - CNT_CHILDREN,
         CHILDRENperADULT = CNT_CHILDREN / ADULTS,
         INCOMEperADULT = AMT_INCOME_TOTAL / ADULTS,
         EMPLOYMENTratio = DAYS_EMPLOYED / (DAYS_BIRTH - 6500),
         EXT_SOURCE_0 = EXT_SOURCE_1 * EXT_SOURCE_2 * EXT_SOURCE_3)
```


```{r}
trainID <- train$SK_ID_CURR
#trainID <- data.frame(trainID)
names(trainID)[1] <- "SK_ID_CURR"
#trainmodel <- merge(trainID, joint, by = "SK_ID_CURR")
#trainmodel <- joint[joint$SK_ID_CURR %in% trainID,]
trainmodel <- filter(joint, SK_ID_CURR %in% trainID)
trainmodel <- merge(knownTarget, trainmodel, by = "SK_ID_CURR")
```



```{r}
#trainmodel$NAME_CONTRACT_TYPE <- joint$NAME_CONTRACT_TYPE
##trainmodel$CODE_GENDER <- joint$CODE_GENDER
#trainmodel$FLAG_OWN_CAR <- joint$FLAG_OWN_CAR
#trainmodel$FLAG_OWN_REALTY <- joint$FLAG_OWN_REALTY
#trainmodel$CNT_CHILDREN <- joint$CNT_CHILDREN
#trainmodel$AMT_INCOME_TOTAL <- joint$AMT_INCOME_TOTAL
#rainmodel$AMT_CREDIT <- joint$AMT_CREDIT
#trainmodel$AMT_ANNUITY <- joint$AMT_ANNUITY
#trainmodel$AMT_GOODS_PRICE <- joint$AMT_GOODS_PRICE
#trainmodel$REGION_POPULATION_RELATIVE <- joint$REGION_POPULATION_RELATIVE
#trainmodel$DAYS_BIRTH <- joint$DAYS_BIRTH
#trainmodel$DAYS_EMPLOYED <- joint$DAYS_EMPLOYED
#trainmodel$DAYS_ID_PUBLISH <- joint$DAYS_ID_PUBLISH
#trainmodel$CNT_FAM_MEMBERS <- joint$CNT_FAM_MEMBERS
#trainmodel$REGION_RATING_CLIENT <- joint$REGION_RATING_CLIENT
#trainmodel$REGION_RATING_CLIENT_W_CITY <- joint$REGION_RATING_CLIENT_W_CITY
#trainmodel$WEEKDAY_APPR_PROCESS_START <- joint$WEEKDAY_APPR_PROCESS_START
#trainmodel$EXT_SOURCE_1 <- joint$EXT_SOURCE_1
#trainmodel$EXT_SOURCE_2 <- joint$EXT_SOURCE_2
#trainmodel$EXT_SOURCE_3 <- joint$EXT_SOURCE_3
#trainmodel$EXT_SOURCE_0 <- joint$EXT_SOURCE_0
#trainmodel$ADULTS <- joint$ADULTS
#trainmodel$CHILDRENperADULT <- joint$CHILDRENperADULT
#trainmodel$INCOMEperADULT <- joint$INCOMEperADULT
#trainmodel$EMPLOYMENTratio <- joint$EMPLOYMENTratio
```


```{r}
model <- gbm(TARGET ~ .,data=trainmodel, n.trees = 150,  cv.folds = 3, verbose = TRUE)
```

```{r}
testSK <- test$SK_ID_CURR
testmodel <- filter(joint, SK_ID_CURR %in% testSK)
```

```{r}
#testmodel <- merge(knownTarget, trainmodel, by = "SK_ID_CURR")
predmatrix <- predict(model, testmodel, n.Trees = 500)
```


```{r}
summary(predmatrix)
predmatrix <- data.frame(predmatrix)
predmatrix$SK_ID_CURR <- testmodel$SK_ID_CURR
```

```{r}
write.csv(predmatrix, file ="kaggle_submission_###.csv")

```








